-- Curio schema — the v1 baseline, carried over verbatim from the shipped implementation.
--
-- DO NOT EDIT THIS FILE TO CHANGE THE SCHEMA. It defines the shape a fresh database
-- starts at. Every change after release belongs in `src/migrations.rs` as a new versioned
-- migration. Editing here instead would give new installs the change and existing
-- libraries never — which is exactly the divergence the migration runner exists to
-- prevent, and it has caught that mistake in this codebase before (see migration v3).
--
-- Every statement is IF NOT EXISTS, so applying this to an existing library is a no-op.
-- That is deliberate: the open path runs the baseline and then the migrations, and both
-- must be safe against a database that already has everything.

CREATE TABLE IF NOT EXISTS items (
  id TEXT PRIMARY KEY,                -- ULID
  name TEXT NOT NULL,
  short_description TEXT NOT NULL DEFAULT '',
  source_url TEXT,
  image_recipe TEXT,
  screenshot_path TEXT NOT NULL,      -- relative to data root
  thumbnail_path TEXT,
  status TEXT NOT NULL DEFAULT 'processing'
    CHECK (status IN ('processing','ready','needs_review','assessment_failed')),
  last_edited_by TEXT NOT NULL DEFAULT 'ai' CHECK (last_edited_by IN ('ai','user')),
  error TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS items_status_idx ON items(status);
CREATE INDEX IF NOT EXISTS items_created_idx ON items(created_at DESC);

CREATE TABLE IF NOT EXISTS aesthetic_families (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  description TEXT NOT NULL,          -- gold-standard format
  created_by TEXT NOT NULL CHECK (created_by IN ('ai','user')),
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS design_types (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  created_by TEXT NOT NULL CHECK (created_by IN ('ai','user'))
);

CREATE TABLE IF NOT EXISTS tags (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL UNIQUE COLLATE NOCASE,
  created_by TEXT NOT NULL CHECK (created_by IN ('ai','user'))
);

CREATE TABLE IF NOT EXISTS item_families (
  item_id TEXT NOT NULL REFERENCES items(id) ON DELETE CASCADE,
  family_id TEXT NOT NULL REFERENCES aesthetic_families(id) ON DELETE CASCADE,
  score REAL NOT NULL,                     -- 0.0-1.0, LLM-judged
  gray_zone INTEGER NOT NULL DEFAULT 0,    -- 1 = pending user decision (FR-7)
  ai_proposed INTEGER NOT NULL DEFAULT 0,  -- 1 = family was proposed for this item
  PRIMARY KEY (item_id, family_id)
);

CREATE INDEX IF NOT EXISTS item_families_family_idx ON item_families(family_id);

CREATE TABLE IF NOT EXISTS item_types (
  item_id TEXT NOT NULL REFERENCES items(id) ON DELETE CASCADE,
  type_id TEXT NOT NULL REFERENCES design_types(id) ON DELETE CASCADE,
  PRIMARY KEY (item_id, type_id)
);

CREATE INDEX IF NOT EXISTS item_types_type_idx ON item_types(type_id);

CREATE TABLE IF NOT EXISTS item_tags (
  item_id TEXT NOT NULL REFERENCES items(id) ON DELETE CASCADE,
  tag_id  TEXT NOT NULL REFERENCES tags(id) ON DELETE CASCADE,
  PRIMARY KEY (item_id, tag_id)
);

CREATE INDEX IF NOT EXISTS item_tags_tag_idx ON item_tags(tag_id);

CREATE TABLE IF NOT EXISTS prompts (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  doc_json TEXT NOT NULL,             -- TipTap document
  serialized_text TEXT NOT NULL,      -- plain-text prompt (what gets copied)
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS projects (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  path TEXT NOT NULL UNIQUE,          -- absolute
  origin TEXT NOT NULL DEFAULT 'watcher' CHECK (origin IN ('watcher','mcp','manual')),
  prompt_id TEXT REFERENCES prompts(id),
  status TEXT NOT NULL DEFAULT 'present' CHECK (status IN ('present','missing')),
  detected_at TEXT NOT NULL,
  last_opened_at TEXT
);

CREATE TABLE IF NOT EXISTS jobs (
  id TEXT PRIMARY KEY,
  kind TEXT NOT NULL,
  payload TEXT NOT NULL,              -- JSON
  status TEXT NOT NULL DEFAULT 'queued'
    CHECK (status IN ('queued','running','done','failed','cancelled')),
  attempts INTEGER NOT NULL DEFAULT 0,
  error TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS jobs_status_idx ON jobs(status, created_at);
