//! Composing prompts: the template, and the one authoritative serializer.
//!
//! The dashboard owns the editing experience; this module owns what a prompt *means*. That
//! split is R-FE-18: the SPA stores TipTap JSON and renders friendly chips, and every
//! consumer of the finished text — clipboard, `prompts/{id}.md` snapshot, the MCP
//! `prompt_get` tool — reads it from [`serialize`], so there is exactly one definition of
//! what a chip expands to.

pub mod serialize;
pub mod template;
pub mod title;

pub use serialize::{ChipContext, FamilySample, MAX_SAMPLES, serialize};
pub use template::{SECTIONS, Section, UNTITLED, heading_for, starter_document};
pub use title::title_from;

/// The header written at the top of every `prompts/{id}.md` snapshot.
///
/// Snapshots are a **projection**, like item sidecars: the database is the source of truth
/// and the file is regenerated on every save (R-DA-4). Saying so in the file is the only
/// thing standing between a user editing it and quietly losing that work on the next
/// autosave.
pub const SNAPSHOT_HEADER: &str =
    "<!-- Generated by Curio. Edits here are not read back — edit the prompt in Curio. -->";

/// Render the snapshot written beside a prompt.
#[must_use]
pub fn snapshot(title: &str, serialized_text: &str) -> String {
    format!("{SNAPSHOT_HEADER}\n\n# {title}\n\n{serialized_text}\n")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_snapshot_warns_that_it_is_not_read_back() {
        // The whole reason the header exists: without it, a user edits the markdown file,
        // the next autosave regenerates it, and the work is gone with no error anywhere.
        let rendered = snapshot("Pricing page", "## Brief\n\nA pricing page.");

        assert!(rendered.starts_with(SNAPSHOT_HEADER), "{rendered}");
        assert!(rendered.contains("not read back"));
    }

    #[test]
    fn a_snapshot_carries_the_title_and_the_text() {
        let rendered = snapshot("Pricing page", "## Brief\n\nA pricing page.");

        assert!(rendered.contains("# Pricing page"));
        assert!(rendered.contains("A pricing page."));
        assert!(rendered.ends_with('\n'), "files end with a newline");
    }
}
