//! `item.md` — the library, readable with `cat`.
//!
//! Every item directory carries a markdown sidecar beside its screenshot. This is the
//! zero-integration path the product rests on (FR-5, PRD §1): an agent with no MCP
//! connection and no knowledge of Curio's API can read the entire library with a
//! filesystem walk, because every fact about an item is in a file next to its image.
//!
//! ## Write-only, and that is the whole contract
//!
//! Sidecars are a **projection** (R-DA-4). They are regenerated inside the same
//! transaction as the mutation that changed the item, and on any disagreement the database
//! wins. Nothing here is ever parsed back. That is why the header says so in the file: a
//! user who edits `item.md` and expects it to stick would otherwise lose the edit on the
//! next write, silently.
//!
//! ## Why YAML is emitted by hand
//!
//! A serializer crate would be one more dependency in an idle-footprint budget that counts
//! them (R-BE-31), for a document with six scalar fields and three lists. The quoting rule
//! below is the entire complexity, and it is tested rather than trusted.

use crate::domain::Item;

/// The line at the top of every sidecar.
pub const SIDECAR_HEADER: &str =
    "<!-- Generated by Curio. Edits here are not read back — edit the item in Curio. -->";

/// The sidecar's file name inside an item directory.
pub const SIDECAR_FILE_NAME: &str = "item.md";

/// Render an item's sidecar.
#[must_use]
pub fn render(item: &Item) -> String {
    let mut out = String::with_capacity(512);

    out.push_str(SIDECAR_HEADER);
    out.push_str("\n---\n");
    field(&mut out, "id", &item.id);
    field(&mut out, "name", &item.name);
    optional(&mut out, "source_url", item.source_url.as_deref());
    field(&mut out, "status", item.status.as_str());
    field(&mut out, "last_edited_by", item.last_edited_by.as_str());
    field(&mut out, "screenshot", &item.screenshot_path);
    optional(&mut out, "thumbnail", item.thumbnail_path.as_deref());
    field(&mut out, "created_at", &item.created_at);
    field(&mut out, "updated_at", &item.updated_at);

    list(&mut out, "design_types", &item.design_types);
    list(&mut out, "tags", &item.tags);

    if item.families.is_empty() {
        out.push_str("families: []\n");
    } else {
        out.push_str("families:\n");
        for link in &item.families {
            out.push_str("  - name: ");
            out.push_str(&scalar(&link.name));
            out.push('\n');
            // Two decimals: the score is judged, not measured, and printing 0.8300000001
            // invites a reader to believe in precision that is not there.
            out.push_str(&format!("    score: {:.2}\n", link.score));
            if link.gray_zone {
                out.push_str("    gray_zone: true\n");
            }
            if link.ai_proposed {
                out.push_str("    ai_proposed: true\n");
            }
        }
    }

    out.push_str("---\n\n## Short Description\n\n");
    out.push_str(item.short_description.trim());
    out.push('\n');

    if let Some(recipe) = item
        .image_recipe
        .as_deref()
        .map(str::trim)
        .filter(|r| !r.is_empty())
    {
        out.push_str("\n## Image Recipe\n\n");
        out.push_str(recipe);
        out.push('\n');
    }

    out
}

fn field(out: &mut String, key: &str, value: &str) {
    out.push_str(key);
    out.push_str(": ");
    out.push_str(&scalar(value));
    out.push('\n');
}

fn optional(out: &mut String, key: &str, value: Option<&str>) {
    match value {
        Some(value) if !value.is_empty() => field(out, key, value),
        // `null` rather than omission: a reader scanning for `source_url` learns the item
        // has none, instead of wondering whether the field was ever written.
        _ => {
            out.push_str(key);
            out.push_str(": null\n");
        }
    }
}

fn list(out: &mut String, key: &str, values: &[String]) {
    if values.is_empty() {
        out.push_str(key);
        out.push_str(": []\n");
        return;
    }
    out.push_str(key);
    out.push_str(":\n");
    for value in values {
        out.push_str("  - ");
        out.push_str(&scalar(value));
        out.push('\n');
    }
}

/// Quote a scalar when leaving it bare would change its meaning.
///
/// The cases that matter here are real: a tag called `no` parses as a boolean, a name
/// starting with `#` is a comment, a description containing `: ` splits into a mapping, and
/// a URL is fine bare but a name with a leading space is not. Quoting whenever in doubt is
/// the cheap side of the trade — an over-quoted string reads the same to every parser.
fn scalar(value: &str) -> String {
    const RESERVED_STARTS: &[char] = &[
        '#', '&', '*', '!', '|', '>', '\'', '"', '%', '@', '`', '-', '?', ':', '[', ']', '{', '}',
        ',',
    ];
    let needs_quotes = value.is_empty()
        || value.trim() != value
        || value.contains(": ")
        || value.contains('\n')
        || value.contains('"')
        // A ` #` anywhere starts a comment, so the rest of the value would be discarded on
        // read — the one failure mode that is silent in both directions.
        || value.contains(" #")
        || value.starts_with(RESERVED_STARTS)
        || matches!(
            value.to_ascii_lowercase().as_str(),
            "true" | "false" | "null" | "yes" | "no" | "on" | "off" | "~"
        )
        || value.parse::<f64>().is_ok();

    if !needs_quotes {
        return value.to_owned();
    }
    format!(
        "\"{}\"",
        value
            .replace('\\', "\\\\")
            .replace('"', "\\\"")
            .replace('\n', "\\n")
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::domain::{ItemFamily, ItemStatus, LastEditedBy};

    fn item() -> Item {
        Item {
            id: "01J000000000000000000000".to_owned(),
            name: "Stripe pricing".to_owned(),
            short_description: "A clean pricing table on white.".to_owned(),
            source_url: Some("https://stripe.com/pricing".to_owned()),
            image_recipe: None,
            screenshot_path: "items/01J000000000000000000000/screenshot.png".to_owned(),
            thumbnail_path: None,
            status: ItemStatus::Ready,
            last_edited_by: LastEditedBy::Ai,
            error: None,
            created_at: "2026-01-01T00:00:00Z".to_owned(),
            updated_at: "2026-01-02T00:00:00Z".to_owned(),
            design_types: vec!["pricing page".to_owned()],
            tags: vec!["saas".to_owned(), "minimal".to_owned()],
            families: vec![ItemFamily {
                id: "fam1".to_owned(),
                name: "Warm Editorial".to_owned(),
                score: 0.83,
                gray_zone: false,
                ai_proposed: false,
            }],
        }
    }

    #[test]
    fn the_sidecar_says_it_is_not_read_back() {
        // R-DA-4. Without this line a user edits the file, the next write regenerates it,
        // and the edit is gone with no error anywhere.
        assert!(render(&item()).starts_with(SIDECAR_HEADER));
        assert!(render(&item()).contains("not read back"));
    }

    #[test]
    fn frontmatter_is_delimited_and_carries_every_field() {
        let rendered = render(&item());

        assert!(rendered.contains("\n---\n"), "{rendered}");
        for key in [
            "id:",
            "name:",
            "source_url:",
            "status:",
            "last_edited_by:",
            "screenshot:",
            "created_at:",
            "updated_at:",
            "design_types:",
            "tags:",
            "families:",
        ] {
            assert!(rendered.contains(key), "missing {key} in:\n{rendered}");
        }
    }

    #[test]
    fn a_family_link_carries_its_score_and_flags() {
        let mut subject = item();
        subject.families[0].gray_zone = true;
        subject.families[0].ai_proposed = true;

        let rendered = render(&subject);

        assert!(rendered.contains("score: 0.83"), "{rendered}");
        assert!(rendered.contains("gray_zone: true"), "{rendered}");
        assert!(rendered.contains("ai_proposed: true"), "{rendered}");
    }

    #[test]
    fn settled_links_do_not_carry_noise_flags() {
        // A false flag on every link would triple the frontmatter of a normal item for no
        // information — the absence is the fact.
        let rendered = render(&item());
        assert!(!rendered.contains("gray_zone"), "{rendered}");
    }

    #[test]
    fn empty_lists_are_written_as_empty_lists() {
        // Not omitted: an agent walking the library must be able to tell "no tags" from
        // "this sidecar predates tags".
        let mut subject = item();
        subject.tags.clear();
        subject.design_types.clear();
        subject.families.clear();

        let rendered = render(&subject);

        assert!(rendered.contains("tags: []"), "{rendered}");
        assert!(rendered.contains("design_types: []"), "{rendered}");
        assert!(rendered.contains("families: []"), "{rendered}");
    }

    #[test]
    fn a_missing_source_url_is_null_rather_than_absent() {
        let mut subject = item();
        subject.source_url = None;

        assert!(render(&subject).contains("source_url: null"));
    }

    #[test]
    fn the_short_description_is_a_section() {
        assert!(
            render(&item()).contains("## Short Description\n\nA clean pricing table on white.")
        );
    }

    #[test]
    fn an_image_recipe_appears_only_when_there_is_one() {
        assert!(!render(&item()).contains("Image Recipe"));

        let mut subject = item();
        subject.image_recipe = Some("Wide shot, warm light".to_owned());
        assert!(render(&subject).contains("## Image Recipe\n\nWide shot, warm light"));
    }

    #[test]
    fn an_empty_image_recipe_is_treated_as_none() {
        let mut subject = item();
        subject.image_recipe = Some("   ".to_owned());
        assert!(!render(&subject).contains("Image Recipe"));
    }

    #[test]
    fn names_that_would_parse_as_something_else_are_quoted() {
        // A tag called `no` is a boolean to every YAML parser; a name starting with `#` is
        // a comment; `2026` is a number. Each would change meaning between write and read.
        assert_eq!(scalar("no"), "\"no\"");
        assert_eq!(scalar("true"), "\"true\"");
        assert_eq!(scalar("#brutalist"), "\"#brutalist\"");
        assert_eq!(scalar("2026"), "\"2026\"");
        assert_eq!(scalar("- dash"), "\"- dash\"");
        assert_eq!(scalar(""), "\"\"");
    }

    #[test]
    fn ordinary_names_are_left_bare() {
        assert_eq!(scalar("Stripe pricing"), "Stripe pricing");
        assert_eq!(
            scalar("https://stripe.com/pricing"),
            "https://stripe.com/pricing"
        );
        assert_eq!(
            scalar("items/01J/screenshot.png"),
            "items/01J/screenshot.png"
        );
    }

    #[test]
    fn a_quote_inside_a_name_is_escaped() {
        assert_eq!(scalar("say \"hi\""), "\"say \\\"hi\\\"\"");
    }

    #[test]
    fn a_colon_inside_a_name_forces_quoting() {
        // Bare, `Pricing: the page` parses as a nested mapping and the sidecar stops being
        // valid YAML.
        assert_eq!(scalar("Pricing: the page"), "\"Pricing: the page\"");
    }
}
